Repository Settlers4Modding/CommunityPatchLauncher, pull requests merged in 2021-02, with the labels that each got.

#97 Feature/increase cache time
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/Documentation/Factories/RemoteDocumentManagerFactory.cs
  src/CommunityPatchLauncherFramework/Documentation/Strategy/RemoteDocumentConnectorStrategy.cs
Labels: type > enhancement

#101 Feature/fix cache problem
  src/CommunityPatchLauncher/Documentation/Factories/RemoteDocumentManagerFactory.cs
  src/CommunityPatchLauncher/Properties/Resources.Designer.cs
  src/CommunityPatchLauncher/Properties/Resources.de-DE.resx
  src/CommunityPatchLauncher/Properties/Resources.resx
  src/CommunityPatchLauncherFramework/Documentation/Strategy/RemoteDocumentConnectorStrategy.cs
Labels: backend, type > bug

#102 Feature/fix setting page style
  src/CommunityPatchLauncher/Styles/DefaultStyles.xaml
  src/CommunityPatchLauncher/UserControls/SettingsUserControl.xaml
  src/CommunityPatchLauncher/Windows/WelcomeWindow.xaml
Labels: type > enhancement

#103 Feature/adding checksum
  src/CommunityPatchLauncher/App.config
  src/CommunityPatchLauncher/BindingData/Converter/AcceptAgreementConverter.cs
  src/CommunityPatchLauncher/Commands/DataContainer/AcceptAgreementData.cs
  src/CommunityPatchLauncher/Commands/Settings/AcceptAgreementCommand.cs
  src/CommunityPatchLauncher/Properties/Settings.Designer.cs
  src/CommunityPatchLauncher/Properties/Settings.settings
  src/CommunityPatchLauncher/UserControls/ResizeWindowUserControl.xaml
  src/CommunityPatchLauncher/ViewModels/BrowserModelView.cs
  src/CommunityPatchLauncher/ViewModels/LaunchGameModelView.cs
  src/CommunityPatchLauncher/ViewModels/WelcomeViewModel.cs
  src/CommunityPatchLauncher/Windows/WelcomeWindow.xaml
Labels: type > enhancement

#104 Feature/adding buttons to open tools
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/App.config
  src/CommunityPatchLauncher/Commands/Os/StartEditorCommand.cs
  src/CommunityPatchLauncher/Commands/Os/StartProgramCommand.cs
  src/CommunityPatchLauncher/CommunityPatchLauncher.csproj
  src/CommunityPatchLauncher/Properties/Resources.Designer.cs
  src/CommunityPatchLauncher/Properties/Resources.de-DE.resx
  src/CommunityPatchLauncher/Properties/Resources.resx
  src/CommunityPatchLauncher/Properties/Settings.Designer.cs
  src/CommunityPatchLauncher/Properties/Settings.settings
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
Labels: backend, frontend, type > enhancement

#105 Feature/adding news page
  src/CommunityPatchLauncher/UserControls/BrowserUserControl.xaml.cs
  src/CommunityPatchLauncher/ViewModels/BrowserModelView.cs
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
Labels: backend, frontend, type > enhancement

#106 Feature/correcting news cache time
  src/CommunityPatchLauncher/Documentation/Factories/LocalDocumentManagerFactory.cs
  src/CommunityPatchLauncher/Documentation/Factories/RemoteDocumentManagerFactory.cs
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
Labels: backend

#107 Feature/secure pre installation steps
  src/CommunityLauncherPatcher/Program.cs
  src/CommunityPatchLauncher/Tasks/UnzipAndExtractCommunityPatchTask.cs
  src/CommunityPatchLauncher/Tasks/UnzipCommunityPatchTask.cs
Labels: backend, security, type > enhancement

#108 Feature/maximize on double click
  src/CommunityPatchLauncher/Commands/ApplicationWindow/MaximizeWindowCommand.cs
  src/CommunityPatchLauncher/UserControls/TitleBarUseControl.xaml
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
Labels: type > enhancement

#109 Feature/adding minimize on launch
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/Commands/ApplicationWindow/MinimizeWindowCommand.cs
  src/CommunityPatchLauncher/Commands/Condition/BaseCondition.cs
  src/CommunityPatchLauncher/Commands/Condition/ICondition.cs
  src/CommunityPatchLauncher/Commands/Condition/SpecificSettingSetCondition.cs
  src/CommunityPatchLauncher/CommunityPatchLauncher.csproj
  src/CommunityPatchLauncher/Properties/Resources.Designer.cs
  src/CommunityPatchLauncher/Properties/Resources.de-DE.resx
  src/CommunityPatchLauncher/Properties/Resources.resx
  src/CommunityPatchLauncher/UserControls/LaunchGameUserControl.xaml.cs
  src/CommunityPatchLauncher/UserControls/SettingsUserControl.xaml
  src/CommunityPatchLauncher/ViewModels/LaunchGameModelView.cs
  src/CommunityPatchLauncher/ViewModels/PatchVersionSelectionViewModel.cs
  src/CommunityPatchLauncher/ViewModels/SettingsViewModel.cs
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
Labels: type > enhancement

#110 Add version to main window
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
Labels: type > enhancement

#111 Feature/text and page recheck
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/de-DE/About.md
  docs/de-DE/Agreement.md
  docs/de-DE/CommunityPatch.md
  docs/de-DE/HistoryEdition.md
  docs/de-DE/HistoryEditionPlus.md
  docs/de-DE/Loading.md
  docs/de-DE/NotReadable.md
  docs/en-EN/About.md
  docs/en-EN/Agreement.md
  docs/en-EN/NotReadable.md
  installer/assets/beforeInstall-default.txt
Labels: type > enhancement

#112 Feature/check the text files
  docs/de-DE/About.md
  docs/en-EN/About.md
  docs/pl/About.md
  src/CommunityPatchLauncher/Properties/Resources.de-DE.resx
Labels: type > enhancement

#113 Bug/move files to new download folder
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/Commands/ApplicationWindow/MaximizeWindowCommand.cs
  src/CommunityPatchLauncher/Commands/BaseDataCommand.cs
  src/CommunityPatchLauncher/Commands/Condition/BaseCondition.cs
  src/CommunityPatchLauncher/Commands/Condition/EmptyFolderCondition.cs
  src/CommunityPatchLauncher/Commands/Condition/ICondition.cs
  src/CommunityPatchLauncher/Commands/Condition/IsAvailablePatchCondition.cs
  src/CommunityPatchLauncher/Commands/Condition/SettlerFolderCondition.cs
  src/CommunityPatchLauncher/Commands/Condition/SpecificSettingSetCondition.cs
  src/CommunityPatchLauncher/Commands/DataCommands/InstallationFromManuelSelectionCommand.cs
  src/CommunityPatchLauncher/Commands/DataContainer/AcceptAgreementData.cs
  src/CommunityPatchLauncher/Commands/IDataCommand.cs
  src/CommunityPatchLauncher/Commands/Os/MoveFolderCommand.cs
  src/CommunityPatchLauncher/Commands/Os/OpenFolderCommand.cs
  src/CommunityPatchLauncher/Commands/Os/SelectFolderCommand.cs
  src/CommunityPatchLauncher/Commands/Os/StartProgramCommand.cs
  src/CommunityPatchLauncher/CommunityPatchLauncher.csproj
  src/CommunityPatchLauncher/Enums/ErrorSeverityEnum.cs
  src/CommunityPatchLauncher/EventArguments/DataCommandErrorEventArg.cs
  src/CommunityPatchLauncher/Properties/Resources.Designer.cs
  src/CommunityPatchLauncher/Properties/Resources.de-DE.resx
  src/CommunityPatchLauncher/Properties/Resources.resx
  src/CommunityPatchLauncher/UserControls/InfoPopup.xaml
  src/CommunityPatchLauncher/UserControls/SettingsUserControl.xaml
  src/CommunityPatchLauncher/ViewModels/BrowserModelView.cs
  src/CommunityPatchLauncher/ViewModels/InfoPopupViewModel.cs
  src/CommunityPatchLauncher/ViewModels/LaunchGameModelView.cs
  src/CommunityPatchLauncher/ViewModels/PopupWindowsViewModel.cs
  src/CommunityPatchLauncher/ViewModels/SettingsViewModel.cs
  src/CommunityPatchLauncher/ViewModels/WelcomeViewModel.cs
Labels: type > enhancement

#114 Bug/fix crash if uac blocked for editor
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/Commands/Os/StartEditorCommand.cs
  src/CommunityPatchLauncher/Commands/Os/StartProgramCommand.cs
Labels: type > enhancement

#115 Feature/extend browser window
  docs/en-EN/Changelog.md
  docs/en-EN/Changelogs/Showcase.md
  src/CommunityPatchLauncher/ViewModels/BrowserModelView.cs
Labels: type > enhancement

#116 Adding license to launcher
  src/CommunityPatchLauncher/CommunityPatchLauncher.csproj
  src/CommunityPatchLauncher/Properties/Resources.Designer.cs
  src/CommunityPatchLauncher/Properties/Resources.de-DE.resx
  src/CommunityPatchLauncher/Properties/Resources.resx
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
Labels: type > enhancement

#117 Feature/improve markdown content
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/Styles/DefaultBrowserStyle.css
Labels: type > enhancement

#119 Feature/fix maximize problem
  src/CommunityPatchLauncher/UserControls/TitleBarUseControl.xaml
  src/CommunityPatchLauncher/ViewModels/BaseViewModel.cs
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
  src/CommunityPatchLauncher/ViewModels/WelcomeViewModel.cs
  src/CommunityPatchLauncher/Windows/WelcomeWindow.xaml
Labels: type > enhancement

#120 Reafctor/unify browser windows
  src/CommunityPatchLauncher/Commands/ApplicationWindow/ChangeBrowserContentCommand.cs
  src/CommunityPatchLauncher/Commands/ApplicationWindow/OpenControlToPanel.cs
  src/CommunityPatchLauncher/Commands/Os/MoveFolderCommand.cs
  src/CommunityPatchLauncher/CommunityPatchLauncher.csproj
  src/CommunityPatchLauncher/UserControls/BrowserUserControl.xaml.cs
  src/CommunityPatchLauncher/UserControls/LaunchGameUserControl.xaml
  src/CommunityPatchLauncher/ViewModels/BrowserModelView.cs
  src/CommunityPatchLauncher/ViewModels/LaunchGameModelView.cs
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
  src/CommunityPatchLauncher/ViewModels/WelcomeViewModel.cs
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
  src/CommunityPatchLauncher/Windows/WelcomeWindow.xaml
  src/CommunityPatchLauncherFramework/Documentation/Strategy/RemoteDocumentConnectorStrategy.cs
Labels: type > enhancement

#122 Bugfix/request admin rights if needed
  src/CommunityPatchLauncher/Tasks/Update/PatchLauncher.cs
Labels: type > bug

#123 Fixing crash on update
  src/CommunityPatchLauncher/Tasks/Factories/UpdateClientFactory.cs
  src/CommunityPatchLauncher/Tasks/Update/PatchLauncher.cs
Labels: type > bug

#124 Fix the save bug
  src/CommunityPatchLauncher/Commands/Os/MoveFolderCommand.cs
  src/CommunityPatchLauncher/Commands/Settings/SaveSettingsCommand.cs
  src/CommunityPatchLauncher/ViewModels/SettingsViewModel.cs
Labels: type > bug

#129 Fix bugs
  src/CommunityLauncherPatcher/Program.cs
Labels: backend, type > bug

#128 Added Open MP Folder and Savegame Folder
  docs/en-EN/Changelog.md
  src/CommunityPatchLauncher/Properties/Resources.Designer.cs
  src/CommunityPatchLauncher/Properties/Resources.de-DE.resx
  src/CommunityPatchLauncher/Properties/Resources.resx
  src/CommunityPatchLauncher/ViewModels/MainWindowModel.cs
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
Labels: frontend

#132 Change default size
  src/CommunityPatchLauncher/Windows/MainWindow.xaml
  src/CommunityPatchLauncher/Windows/WelcomeWindow.xaml
Labels: type > enhancement

#131 Fix not loading agreement
  docs/pl/Agreement.md
  docs/pl/deleteMe.txt
  src/CommunityPatchLauncher/Commands/Settings/SaveSettingsCommand.cs
  src/CommunityPatchLauncher/ViewModels/WelcomeViewModel.cs
Labels: type > bug
